src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Entity\Board;

/**
 * A user.
 * @ApiResource()
 * @ORM\Entity()
 * @UniqueEntity(fields="phone", message="{{ value }} is already in use by another user.")
 * @UniqueEntity(fields="email", message="{{ value }} is already in use by another user.")
 */

class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", unique=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $gender;

    /**
     * @ORM\OneToMany(targetEntity="Board", mappedBy="userId", cascade={"all"}, orphanRemoval=true)
     * @ApiSubresource
     */
    private $boards;

    /**
     * @ORM\Column(type="boolean")
     */
    private $confirmed;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $facebookId;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $githubId;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $gravatar;

    public function __construct()
    {
        $this->roles[] = 'ROLE_USER';
        $this->lists = new ArrayCollection();
        $this->confirmed = false;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;
        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;
        $this->setGravatar($email);
        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;
        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;
        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;
        return $this;
    }

    public function getFacebookId(): ?string
    {
        return $this->facebookId;
    }

    public function setFacebookId(?string $fb): self
    {
        $this->facebookId = $fb;
        return $this;
    }

    public function getGithubId(): ?string
    {
        return $this->githubId;
    }

    public function setGithubId(?string $github): self
    {
        $this->githubId = $github;
        return $this;
    }

    public function getBoards(): Collection
    {
        return $this->boards;
    }

    public function addBoard(Board $board): self
    {
        if (!$this->boards->contains($board)) {
            $this->boards[] = $board;
            $board->setUserId($this);
        }
        return $this;
    }

    public function removeBoard(Board $board): self
    {
        if ($this->boards->contains($board)) {
            $this->boards->removeElement($board);
            if ($board->getUserId() === $this) {
                $board->setUserId(null);
            }
        }
        return $this;
    }

    public function getConfirmed(): bool
    {
        return $this->confirmed;
    }

    public function setConfirmed(bool $confirmed): self
    {
        $this->confirmed = $confirmed;
        return $this;
    }

    public function getGravatar(): ?string
    {
        return $this->gravatar;
    }

    public function setGravatar(string $email): self
    {
        $grav_url =
            "https://www.gravatar.com/avatar/" .
            md5(strtolower(trim($email))) .
            "?d=https://todone.local/images/placeholder.png&s=500";
        $this->gravatar = $grav_url;
        return $this;
    }

    public function getSalt()
    {
    }

    public function eraseCredentials()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }
}

templates/auth.twig
{#
@name:          auth.twig
@description:   Base template for the auth portion of the site.
#}

<!DOCTYPE html>
<html lang="en">	
<head>	
  <title>{% block title %}ToDone!{% endblock %}</title>
  <meta name="description" content="{% block description %}To do lists Yay!{% endblock %}">
  <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="images/favicon.png">
  {% block assets %}
			<link rel="stylesheet" href="{{ asset('/assets/auth.css') }}">
	{% endblock %}
</head>
<body class='auth {% block bodyClass %}{% endblock %}'>
<section id="vue" class="hero is-light is-fullheight">
  <div class="hero-head">
    <nav class="navbar fixed w-100">
      <div class="container">
        <div class="navbar-brand">
          <a href='/' class="navbar-item active">
           	<span class='has-text-weight-bold has-text-info is-size-3'>to<span class='has-text-primary'>done</span></span>
          </a>
          <span class="navbar-burger burger has-text-primary" data-target="frontNav">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="frontNav" class="navbar-menu has-background-grey-dark has-text-grey">
          <div class="navbar-end">
            <a href='/' class="navbar-item {% if active == 'home' %}is-active{% endif %}">Home</a>
            <a href='/about' class="navbar-item {% if active == 'about' %}is-active{% endif %}">About</a>
            <a href='/contact' class="navbar-item {% if active == 'contact' %}is-active{% endif %}">Contact</a>
            <a href="/login" class="respond navbar-item {% if active == 'login' %}is-active{% endif %}">Login</a>
            <a href="/signup" class="respond navbar-item {% if active == 'signup' %}is-active{% endif %}">Signup</a>
            <hr class="respond m-top-0 m-bottom-0">
            <div class="dropdown is-right m-left-15 is-hoverable">
              <div class="dropdown-trigger">
                <button class="button is-primary">
                  <span class="icon"><i class="fa fa-user-plus"></i></span>
                  <span>Login</span>
                </button>
              </div>
              <div class="dropdown-menu p-top-0" id="dropdown-menu2" role="menu">
                <div class="dropdown-content">
                  <a href="/login" class="dropdown-item">Log In</a>
                  <hr class="dropdown-divider">
                  <a href="/signup" class="dropdown-item">Sign Up</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>	
	<div class="hero-body">
      <div id="auth" class="container">
        {% block main %}
        {% endblock %}
      </div>
    </div>
	<div class="hero-foot">
    <nav class="tabs is-boxed is-fullwidth">
      <div class="container">
        <ul>
          <li class="is-active"><a class='has-background-grey-dark has-text-white' href='https://www.brennanwal.sh'>Made with <span class='fa fa-heart has-text-primary'></span>by Brennan Walsh</a> </li>
          <li><a href='/privacy'>Privacy</a></li>
          <li><a href='/terms'>Terms</a></li>
        </ul>
      </div>
    </nav>
  </div>
  {% for label, messages in app.flashes(['success', 'danger', 'warning', 'info']) %}
    {% for message in messages %}
      <message-component classtype="is-{{ label }}" value="{{message}}"></message-component>
    {% endfor %}
  {% endfor %}
  <message-component></message-component>
</section>
{% block scripts %}
    <script src="{{ asset('/assets/runtime.js') }}"></script>  
	<script src="{{ asset('/assets/auth.js') }}"></script>
{% endblock %}
</body>	
</html>

templates/dash.twig
<!DOCTYPE html>
<html lang="en">

<head>
	<title>{% block title %}ToDone!{% endblock %}</title>
	<meta name="description" content="{% block description %}To do lists Yay!{% endblock %}">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="/images/favicon.png">
	<link rel="stylesheet" href="{{ asset('/assets/dash.css') }}">
</head>

<body class='dash {% block bodyClass %}{% endblock %}'>
  <div id="vue">
	{% if app.user.confirmed != 1 %}
	<section id="confirm" class='fixed has-background-black has-text-centered w-100'>
		<div class="container">
			<p class='has-text-light'>Please confirm your email. We've emailed a confirmation link to {{app.user.email}}. <a class='has-text-primary' href="/confirm?resend=true&route={{app.request.get('_route')}}">Click here to resend it</a>.</p>
		</div>
	</section>
	{% endif %}
	<section id='topbar'>
		<nav class="navbar has-background-grey-dark fixed w-100	{% if app.user.confirmed != 1 %}confirm	{% endif %}">
			<div class='container is-fluid'>
				<div class="navbar-brand">
					<a class="navbar-item p-top-0 p-bottom-0" href="/boards/">
						<span class='has-text-weight-bold has-text-info is-size-3'>to<span class='has-text-primary'>done</span></span>
					</a>
					<a role="button" class="navbar-burger burger has-text-primary" data-target="sidebar">
						<span aria-hidden="true"></span>
						<span aria-hidden="true"></span>
						<span aria-hidden="true"></span>
					</a>
				</div>
				<div class="navbar-menu">
					<div class="navbar-end">
						<div class="dropdown is-right m-left-15 is-hoverable">
							<div class="dropdown-trigger">
								<button class="button is-primary">
									<span class="icon"><i class="fa fa-user"></i></span>
									<span>{{ app.user.username }}</span>
								</button>
							</div>
							<div class="dropdown-menu p-top-0" id="dropdown-menu2" role="menu">
								<div class="dropdown-content">
									<a href="/" class="dropdown-item">Front</a>
									<a href="/logout" class="dropdown-item">Logout</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</section>
	<section id='dash' class='{% if app.user.confirmed != 1 %}m-top-30{% endif %}'>
		<div class='columns m-bottom-0'>
			<aside id='sidebar' class="menu p-left-0 p-right-0 column is-5-mobile is-3-tablet is-2-desktop has-background-black h-100">
				<p class="menu-label">Navigation
				</p>
				<ul class="menu-list">
					<li><a href='/boards' class='{% if active == "boards" %}is-active{% endif %}'>Boards</a></li>
					<li><a href='/profile' class='{% if active == "profile" %}is-active{% endif %}'>Profile</a></li>
				</ul>
				<p class="menu-label"><span @click.prevent="$refs.create.open()" class="createbutton has-text-primary is-pulled-left m-left-15"><i class="fa fa-plus m-left-0 m-right-5"></i> Board</span> Your Boards</p>
				<sidebar id='sidelists' class="menu-list" active="{{active}}">
				</sidebar>
			</aside>
			<div id="main" class='main column is-12 is-10-desktop is-offset-2-desktop'>
				{% block main %}
				{% endblock %}
			</div>
			<create-modal ref="create"></create-modal>
			<delete-modal ref="delete"></delete-modal>
			<edit-modal ref="edit"></edit-modal>
		</div>
	</section>
    {% for label, messages in app.flashes(['success', 'danger', 'warning', 'info']) %}
      {% for message in messages %}
      <message-component classtype="is-{{ label }}" value="{{message}}"></message-component>
      {% endfor %}
    {% endfor %}
    <message-component></message-component>
  </div>
  <script src="{{ asset('/assets/runtime.js') }}"></script>  
  <script src="{{ asset('/assets/dash.js') }}"></script>
</body>

</html>

templates/front.twig
{#
# @name: front.twig
# @description: Base template for the frontend of the site.
#}

<!DOCTYPE html>
<html lang="en">

<head>
	 <title>ToDone! {% block title %}An organization and productivity app.{% endblock %}</title>
	<meta name="description" content="{% block description %}ToDone! is an organization and productivity application similar to Trello.{% endblock %}">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" href="images/favicon.png">
	{% block assets %}
	<link rel="stylesheet" href="{{ asset('/assets/front.css') }}">
	{% endblock %}
</head>

<body class='front {% block bodyClass %}{% endblock %}'>
	<section id="vue" class="hero is-light is-fullheight">
		<div class="hero-head">
			<nav class="navbar has-background-grey-dark fixed w-100">
				<div class="container">
					<div class="navbar-brand">
						<a href='/' class="navbar-item active">
							<span class='has-text-weight-bold has-text-info is-size-3'>to<span class='has-text-primary'>done</span></span>
						</a>
						<span id="burger" class="navbar-burger burger has-text-primary" data-target="frontNav">
							<span></span>
							<span></span>
							<span></span>
						</span>
					</div>
					<div id="frontNav" class="navbar-menu has-background-grey-dark has-text-grey">
						<div class="navbar-end">
							<a href='/' class="navbar-item {% if active == 'home' %}is-active{% endif %}">Home</a>
							<a href='/about' class="navbar-item {% if active == 'about' %}is-active{% endif %}">About</a>
							<a href='/contact' class="navbar-item {% if active == 'contact' %}is-active{% endif %}">Contact</a>
							{% if is_granted('ROLE_USER') %}
							<a href="/dashboard" class="respond navbar-item">Dashboard</a>
							<a href="/logout" class="respond navbar-item">Log out</a>
							{% else %}
							<a href="/login" class="respond navbar-item">Login</a>
							<a href="/signup" class="respond navbar-item">Signup</a>
							{% endif %}
							{% if is_granted('ROLE_USER') %}
							<div class="dropdown is-right m-left-15 is-hoverable">
								<div class="dropdown-trigger">
									<button class="button is-primary">
										<span class="icon"><i class="fa fa-user"></i></span>
										<span>{{ app.user.username }}</span>
									</button>
								</div>
								<div class="dropdown-menu p-top-0" id="dropdown-menu2" role="menu">
									<div class="dropdown-content">
										<a href="/boards" class="dropdown-item">Dashboard</a>
										<hr class="dropdown-divider">
										<a href="/logout" class="dropdown-item">Logout</a>
									</div>
								</div>
							</div>
							{% else %}
							<div class="dropdown is-right m-left-15 is-hoverable">
								<div class="dropdown-trigger">
									<button class="button is-primary">
										<span class="icon"><i class="fa fa-user-plus"></i></span>
										<span>Login</span>
									</button>
								</div>
								<div class="dropdown-menu p-top-0" id="dropdown-menu2" role="menu">
									<div class="dropdown-content">
										<a href="/login" class="dropdown-item">Log In</a>
										<hr class="dropdown-divider">
										<a href="/signup" class="dropdown-item">Sign Up</a>
									</div>
								</div>
							</div>
							{% endif %}
						</div>
					</div>
				</div>
			</nav>
		</div>
		<div class="hero-body">
			<div id="front" class="container">
				{% block main %}
				{% endblock %}
			</div>
		</div>
		<div class="hero-foot">
			<nav class="tabs is-boxed is-fullwidth">
				<div class="container">
					<ul>
						<li class="is-active"><a href='https://www.brennanwal.sh' class='has-background-grey-dark has-text-white'>Built with <span class='fa fa-heart has-text-primary'></span>by Brennan Walsh</a> </li>
						<li><a href='/privacy'>Privacy</a></li>
						<li><a href='/terms'>Terms</a></li>
					</ul>
				</div>
			</nav>
		</div>
        {% for label, messages in app.flashes(['success', 'danger', 'warning', 'info']) %}
          {% for message in messages %}
            <message-component classtype="is-{{ label }}" value="{{message}}"></message-component>
          {% endfor %}
        {% endfor %}
        <message-component></message-component>
	</section>
	{% block scripts %}
    <script src="{{ asset('/assets/runtime.js') }}"></script>  
	<script src="{{ asset('/assets/front.js') }}"></script>
	{% endblock %}
</body>

</html>